#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 22 18:53:35 2022

@author: jiancui
"""

#%% 练习1
# 1.出现语法错误
# 2.语法错误，字符串引号需要成对出现
# 3.单独输入-2，程序可以运行，单独输入2++2也可以运行，若输入print(2++2)也可以进行运行
# 4.数字开头用0会报错
# 5.若两个数字中间无运算符且有空格的情况下(2 2)，则会报错，若加上运算符，则可以运行



#%% 练习2
# 1.计算42min42s
s=60*42+42
print(s) #s=2562s

# 2.  1.6 kilometer=1 mile
s1=10/1.6
print(s1)  #s1=6.25

# 3.
per_mile_seconds=s/s1
print(per_mile_seconds)  #一英里需要409.92秒

per_mile_minutes=(per_mile_seconds)/60
print(per_mile_minutes)   #跑一英里需要6.832分钟

hour=s/3600
print(hour)
ave_hour_speed=s1/hour
print(ave_hour_speed)   #每小时可跑8.8公里
